RentAFlik_Main/src/beans/RegisterBean.java
package beans;

public class RegisterBean {

 // Applying all variables from registration.
 private String nickname;
 private String emailaddress;
 private String password;
 private String firstname;
 private String lastname;
 private String phone;
 
 // Getters which are public strings and setters which are public voids. 
 public String getNickname() {
 return nickname;
 }
 public void setNickname(String nickname) {
 this.nickname = nickname;
 }
 public String getEmailAddress() {
 return emailaddress;
 }
 public void setEmailAddress(String emailaddress) {
 this.emailaddress = emailaddress;
 }
 public String getPassword() {
 return password;
 }
 public void setPassword(String password) {
 this.password = password;
 }
 public String getFirstName() {
 return firstname;
 }
 public void setFirstName(String firstname) {
 this.firstname = firstname;
 }
 public String getLastName() {
 return lastname;
 }
 public void setLastName(String lastname) {
 this.lastname = lastname;
 }
 public String getPhone() {
 return phone;
 }
 public void setPhone(String phone) {
 this.phone = phone;
 }
}

RentAFlik_Main/WebContent/About.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">We rent movies at a great price!!!</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/Contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">1-800-rnt-flik</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/FailedLogin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Failed Login</title>
</h:head> 
	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
	Failed login.
	</body> 
	</ui:define>	
	</ui:composition> 
</html>

RentAFlik_Main/WebContent/LoginPage.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>Login Page</title>
</h:head> 

	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 			

<h:form id="loginForm">
<!--The login page takes in the user submitted data and calls on the login()
	function with the User.java class. A standard inputText is used for the 
	username while inputSecret is used for the password as per standard with 
	passwords. -->
	<h:outputLabel value="username" /> &nbsp;
	<h:inputText style="width:100px;" value="#{EnterpriseUser.userName}" /><br /><br />
	<h:outputLabel value="password"/> &nbsp;
	<h:inputSecret style="width:100px;" value="#{EnterpriseUser.password}"></h:inputSecret><br /><br />
	<h:commandButton action="#{EnterpriseUser.login}" value="Login"></h:commandButton>&nbsp;
	<h:button value="Register" outcome="UpdatedRegisrationForm.jsp"></h:button>
</h:form>
</body> 
    </ui:define>	
	</ui:composition> 

</html>

RentAFlik_Main/WebContent/MainForm.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<title>RentAFlik Video Rentals</title>
	<style>
	body {background-color: #acc;}
	h1   {color: blue;}
	
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 16px;
  text-decoration: none;
  font-size:16px;
}

li a:hover {
  background-color: #111111;
}
	
#SearchLabel {
   display: block;
  color: white;
  text-align: right;
  padding: 16px;
  text-decoration: none;
  font-size:25px;
}	
#SearchTextBox {
  display: block;
  padding: 16px;
  float: left;
  margin: 0;
}		
#logoImg {
  padding: 5px;
  display: block;
}	



#videoList {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  width:100%;
  margin: auto;
  overflow-x:scroll;
  overflow-y:hidden;
  background-color: #888888;
}

#vidImg {
  flex: 0 0 auto;
  margin: auto;
  padding: 3px;
}


	</style></h:head> 

<body>
<h:form>
	<ul>
		<li id="logoImg"><h:graphicImage id="logoImage" width="84px" height="66.5px" value="/images/Logo.PNG"/> </li>
  		<li><a href="MainForm.xhtml">Home</a></li>
  		<li><a href="News.xhtml">News</a></li>
  		<li><a href="Contact.xhtml">Contact</a></li>
  		<li><a href="About.xhtml">About</a></li>
  		<li id="SearchTextBox"><h:inputText style="font-size:16px; width:200px;" value=""/></li>
  		<li style="display:block; text-align:center; margin-top: 16px; margin-left: 0px;"><h:commandButton value="Search" /></li>
  		<li><a style="float:right;" href="LoginPage.xhtml">Login</a></li>
  		<li><a href="NewProduct.xhtml">Add Products</a></li>
	</ul><p></p>


	<label id ="newRelLabel" style="font-size:25px; color:#111111; margin-top:10px; padding:0;">New Releases:</label>
		<ul id="videoList">
			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG" alt="" /></li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
		</ul><p></p><p></p>


	<label id ="newRelLabel" style="font-size:25px; color:#111111; margin-top:10px; padding:0;">Most Popular:</label>

		<ul id="videoList">
			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG" alt="" /></li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
  			<li id="vidImg"><h:graphicImage value="/images/ComingSoon.PNG"/> </li>
		</ul>

	</h:form>
	<ui:insert name = "commonFooter" >
    	<ui:include src = "/layouts/commonFooter.xhtml" />
    </ui:insert>
</body> 
</html>

RentAFlik_Main/WebContent/NewProduct.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
	
	
		<!-- This form is used to add products -->
		<h:form id="newProductForm">
		<h:panelGrid columns="3">
		<h:outputLabel value="Movie Title:" /> 
		<h:inputText value="#{product.title}" /><br /><br />
		<h:outputLabel value="Genre:" />
		<h:inputText value="#{product.genre}" /><br /><br />
		<h:outputLabel value="Lead Actor:" />
		<h:inputText value="#{product.leadAct}" /><br /><br />
		<h:outputLabel value="Studio:" />
		<h:inputText value="#{product.studio}" /><br /><br />
		<h:outputLabel value="Director:" />
		<h:inputText value="#{product.director}" /><br /><br />
		<h:outputLabel value="Length:" />
		<h:inputText value="#{product.length}" /><br /><br />
		<h:outputLabel value="Release Year:" />
		<h:inputText value="#{product.year}" /><br /><br />
		<h:outputLabel value="Rental Price $:" />
		<h:inputText value="#{product.price}" /><br /><br />
		<h:outputLabel value="Video Image File (.PNG):" />
		<h:inputText value="#{product.vidImg}" /><br /><br />
		</h:panelGrid>
		<h:commandButton action="#{productss.addProd(product)}" value="Add Product" /><br/><br/>
		
		<!-- Creates the table below the form with populated data -->
			<h:dataTable value = "#{productss.productss}" var = "odr"
            styleClass = "order-table"
            headerClass = "order-table-header"
            rowClasses = "order-table-odd-row,order-table-even-row">
            
            <h:column>    				
               <f:facet name = "header">Movie Title</f:facet>    				
               #{odr.title}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Genre</f:facet>
               #{odr.genre}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Lead Actor</f:facet>
               #{odr.leadAct}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Production Studio</f:facet>
               #{odr.studio}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Director</f:facet>
               #{odr.director}
            </h:column>
            
            <h:column>
               <f:facet name = "header">Length</f:facet>
               #{odr.length}
            </h:column>
            <h:column>
               <f:facet name = "header">Year</f:facet>
               #{odr.year}
            </h:column>
            <h:column>
               <f:facet name = "header">Rental Price $</f:facet>
               #{odr.price}
            </h:column>
            <h:column>
               <f:facet name = "header">Video Image File</f:facet>
               #{odr.vidImg}
            </h:column>
            </h:dataTable>		
		
		
		</h:form>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/NewRegistration.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 
     <ui:define name="tags"></ui:define>
<h:head>
<title> JSF Form Page</title>
</h:head> 
 <ui:composition>
<body> 
<form action="MainFormController" method="post">
<label>User Name:</label>
<h:inputText value="#{EnterpriseRegistration.userName}" name = "userName"/><br/>
<label>Email Address:</label>
<h:inputText value="#{EnterpriseRegistration.emailAddress}" name="emailAddress"/><br/>
<label>Password:</label>
<h:inputSecret value="#{EnterpriseRegistration.passWord}" name="password"/><br/>
<label>First Name:</label>
<h:inputText value="#{EnterpriseRegistration.firstName}" name="firstName"/><br/>
<label>LastName:</label>
<h:inputText value="#{EnterpriseRegistration.lastName}" name = "lastName"/><br/>
<input type="submit" value="Submit"/>
</form>
</body> 
</ui:composition>
</html>

RentAFlik_Main/WebContent/News.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
				<h3 style="text-align:center;">No News Today!</h3>
	</body> 
	</ui:define>	
</ui:composition>
</html>

RentAFlik_Main/WebContent/Registration.jsp
<pre><%@ page language="java" contentType="text/html; charset=ISO-8859-1"
 pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Register an account:</title>
<script> 
function validate()
{
 // Necessary variables for registration except for phone which is optional.
 var nickname = document.form.nickname.value;
 var emailaddress = document.form.emailaddress.value;
 var password = document.form.password.value;
 var confirmpassword= document.form.confirmpassword.value;
 var firstname = document.form.firstname.value;
 var lastname = document.form.lastname.value;
 var phone = document.form.phone.value;

 // If a variable is empty, the user is warned.
 if (nickname == "" || nickname == null)
 { 
 alert("Please enter a nickname."); 
 return false; 
 }
 else if (emailaddress == "" || emailaddress == null)
 { 
 alert("Please enter an email address.");
 return false; 
 }
 else if(password.length <= 7) // Password strength feature.
 { 
 alert("Make sure your password is 8 characters long or more."); 
 return false; 
 } 
 else if (confirmpassword != password)
 { 
 alert("Passwords do not match."); 
 return false; 
 }
 else if (firstname == "" || firstname == null)
 { 
 alert("Please enter a first name."); 
 return false;
 }
 else if (lastname == "" || lastname == null)
 { 
 alert("Please enter a last name.");
 return false; 
 }
 }

/* Left-aligned fonts, heading 1 used for "Register an account"Array
and arial used for most text in blue background. Buttons needed. */
</script> 
</head>
<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
<body>
<h1 align = "left">Register an account:</h1>
<BODY BGCOLOR="#AACBCC">
<form name="form" action="RegisterServlet" method="post" onsubmit="return validate()">
<table align="left">
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Nickname:</p></td>
 <td><input type="text" name="nickname" /></td>
 </tr>
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Email address:</p></td>
 <td><input type="text" name="emailaddress" /></td>
 </tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Password:</p></td>
 <td><input type="password" name="password" /></td>
 </tr>
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Password confirmation:</p></td>
 <td><input type="password" name="confirmpassword" /></td>
 </tr>
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">First name:</p></td>
 <td><input type="text" name="firstname" /></td>
 </tr>
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Last name:</p></td>
 <td><input type="text" name="lastname" /></td>
 </tr>
 <tr>
 <td><p style = "font-family:arial;font-size:14px;font-style:bold;">Phone number (optional):</p></td>
 <td><input type="text" name="phone" /></td>
 </tr>
 <tr>
 <td><%=(request.getAttribute("errMessage") == null) ? ""
 : request.getAttribute("errMessage")%></td>
 </tr>
 <tr>
 <td></td>
 <td><input type="submit" value="Submit"></input><input
 type="reset" value="Clear"></input></td>
 </tr>
</table>
</form>
</body>
	</ui:define>	
	</ui:composition> 
</html>

RentAFlik_Main/WebContent/SuccessfulLogin.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 
<!--Basic successful login screen. Upon merging the application will
	redirect to the logged in state of the application.-->
<h:head>
<title>Successful Login</title>
</h:head> 
	<ui:composition template = "/layouts/commonLayout.xhtml">	
	<ui:define name = "commonContent">
	<body style="background-color: #acc"> 
	Welcome! You successfully logged into our service!
	</body> 
 	</ui:define>	
	</ui:composition> 
</html>

RentAFlik_Main/WebContent/TestResponse.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

<body>
<p>Hello #{EnterpriseRegistration.firstName} #{EnterpriseRegistration.lastName}</p>
</body>
</html>

RentAFlik_Main/WebContent/UpdatedRegisrationForm.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Registration Form</title>
</head>
<body>
<form action="TestServlet" method="POST">
<label>User Name:</label><br/>
<input type="text" name="userName"/><br/>
<label>Email Address:</label><br/>
<input type="text" name="emailAddress"/><br/>
<label>Password:</label><br/>
<input type="password" name="password"/><br/>
<label>First Name:</label><br/>
<input type="text" name="firstName"/><br/>
<label>Last Name:</label><br/>
<input type="text" name="lastName"/><br/>
<label>Phone Number:</label><br/>
<input type="text" name="phoneNumber"/><br/><br/>
<input type="submit" value="Submit"/>
</form>
</body>
</html>